# JWT 비밀 키 설정 추가
jwt:
  secret: your-super-secret-key-that-is-long-and-secure-enough-for-hs256

server:
  port: 8080 # Spring Boot 웹 서버의 기본 포트: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - profile
              - email